"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

export type LanguageCode = "en" | "es" | "fr" | "de" | "it" | "pt" | "ru" | "zh" | "ja" | "ko" | "ar" | "hi" | "nl"

interface Language {
  code: LanguageCode
  name: string
  nativeName: string
  flag: string
  direction: "ltr" | "rtl"
  region: string
  fontFamily: string
}

interface LanguageContextType {
  language: Language
  setLanguage: (code: LanguageCode) => void
  availableLanguages: Language[]
  t: (key: string) => string
}

const languages: Record<LanguageCode, Language> = {
  en: {
    code: "en",
    name: "English",
    nativeName: "English",
    flag: "🇺🇸",
    direction: "ltr",
    region: "North America",
    fontFamily: "sans-serif",
  },
  es: {
    code: "es",
    name: "Spanish",
    nativeName: "Español",
    flag: "🇪🇸",
    direction: "ltr",
    region: "Europe",
    fontFamily: "sans-serif",
  },
  fr: {
    code: "fr",
    name: "French",
    nativeName: "Français",
    flag: "🇫🇷",
    direction: "ltr",
    region: "Europe",
    fontFamily: "sans-serif",
  },
  de: {
    code: "de",
    name: "German",
    nativeName: "Deutsch",
    flag: "🇩🇪",
    direction: "ltr",
    region: "Europe",
    fontFamily: "sans-serif",
  },
  it: {
    code: "it",
    name: "Italian",
    nativeName: "Italiano",
    flag: "🇮🇹",
    direction: "ltr",
    region: "Europe",
    fontFamily: "sans-serif",
  },
  pt: {
    code: "pt",
    name: "Portuguese",
    nativeName: "Português",
    flag: "🇵🇹",
    direction: "ltr",
    region: "Europe",
    fontFamily: "sans-serif",
  },
  ru: {
    code: "ru",
    name: "Russian",
    nativeName: "Русский",
    flag: "🇷🇺",
    direction: "ltr",
    region: "Europe",
    fontFamily: "sans-serif",
  },
  zh: {
    code: "zh",
    name: "Chinese",
    nativeName: "中文",
    flag: "🇨🇳",
    direction: "ltr",
    region: "Asia",
    fontFamily: "font-chinese",
  },
  ja: {
    code: "ja",
    name: "Japanese",
    nativeName: "日本語",
    flag: "🇯🇵",
    direction: "ltr",
    region: "Asia",
    fontFamily: "sans-serif",
  },
  ko: {
    code: "ko",
    name: "Korean",
    nativeName: "한국어",
    flag: "🇰🇷",
    direction: "ltr",
    region: "Asia",
    fontFamily: "sans-serif",
  },
  ar: {
    code: "ar",
    name: "Arabic",
    nativeName: "العربية",
    flag: "🇸🇦",
    direction: "rtl",
    region: "Asia",
    fontFamily: "font-arabic",
  },
  hi: {
    code: "hi",
    name: "Hindi",
    nativeName: "हिन्दी",
    flag: "🇮🇳",
    direction: "ltr",
    region: "Asia",
    fontFamily: "font-hindi",
  },
  nl: {
    code: "nl",
    name: "Dutch",
    nativeName: "Nederlands",
    flag: "🇳🇱",
    direction: "ltr",
    region: "Europe",
    fontFamily: "sans-serif",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(languages.en)

  useEffect(() => {
    // Load saved language from localStorage on component mount
    const savedLanguage = localStorage.getItem("preferredLanguage") as LanguageCode | null
    if (savedLanguage && languages[savedLanguage]) {
      setCurrentLanguage(languages[savedLanguage])
    }
  }, [])

  const setLanguage = (code: LanguageCode) => {
    if (languages[code]) {
      setCurrentLanguage(languages[code])
      localStorage.setItem("preferredLanguage", code)
    }
  }

  const t = (key: string) => {
    // Access translations based on the current language
    return translations[currentLanguage.code as LanguageCode]?.[key] || key // Fallback to the key if translation is missing
  }

  const availableLanguages = Object.values(languages)

  return (
    <LanguageContext.Provider
      value={{
        language: currentLanguage,
        setLanguage,
        availableLanguages,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

type Translations = {
  [key in LanguageCode]: {
    [key: string]: string
  }
}

export const translations: Translations = {
  en: {
    loading: "Loading...",
    error: "Error",
    success: "Success",
    confirm: "Confirm",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    add: "Add",
    view: "View",
    back: "Back",
    next: "Next",
    previous: "Previous",
    search: "Search",
    clear: "Clear",
    close: "Close",
    open: "Open",
    submit: "Submit",
    reset: "Reset",
    create: "Create",
    update: "Update",
    details: "Details",
    actions: "Actions",
    noData: "No data available",
    pageNotFound: "Page not found",
    unauthorized: "Unauthorized",
    forbidden: "Forbidden",
    internalServerError: "Internal Server Error",
    badRequest: "Bad Request",
    notFound: "Not Found",
    ok: "OK",
    yes: "Yes",
    no: "No",
    today: "Today",
    yesterday: "Yesterday",
    tomorrow: "Tomorrow",
    now: "Now",
    "settings.title": "Settings",
    "settings.currency": "Currency",
    "settings.language": "Language",
    "settings.policy": "Policy",
    "settings.currency.description": "Choose your preferred currency.",
    "settings.language.description": "Select your preferred language.",
    "language.current": "Current",
    "language.select": "Select",
    "language.search": "Search",
    "language.save": "Save",
    "language.changed": "Language changed to",
    "language.preview": "Previewing",
    "language.region": "Region",
    "language.direction": "Direction",
    "language.font": "Font",
    "rooms.add": "Add Room",
    "rooms.edit": "Edit Room",
    "rooms.delete": "Delete Room",
    "rooms.title": "Room",
    "form.roomNumber": "Room Number",
    "form.roomNumber.required": "Room number is required",
    "form.roomNumber.placeholder": "Enter room number",
    "form.category": "Category",
    "form.category.required": "Category is required",
    "form.category.placeholder": "Select a category",
    "form.price.baseNight": "Base Price per Night",
    "form.price.perHour": "Price per Hour",
    "form.price.base": "Base Price",
    "form.price.required": "Price is required",
    "form.price.invalid": "Please enter a valid price",
    "form.description": "Description",
    "form.description.placeholder": "Enter room description",
    "form.images": "Room Images",
    "form.images.remove": "Remove image",
    "form.policy.details": "Policy Details",
    "form.policy.night": "Night Duration",
    "form.policy.checkin": "Check-in Time",
    "form.policy.checkout": "Check-out Time",
    "form.policy.lateCheckout": "Late Check-out Rates",
    "form.policy.earlyCheckin": "Early Check-in Rates",
    "form.policy.configured": "configured",
    "form.policy.baseHours": "Base Hours",
    "form.policy.hours": "hours",
    "form.policy.overtime": "Overtime Rates",
    "form.policy.earlyCheckoutFee": "Early Check-out Fee",
    "form.policy.mixed": "Mixed Policy",
    "form.policy.defaultMode": "Default Booking Mode",
    "form.policy.nightly": "Nightly",
    "form.policy.flexible": "Flexible",
    "form.preview": "Preview",
    "form.clearForm": "Clear Form",
    "form.resetForm": "Reset Form",
    "form.adding": "Adding...",
    "form.updating": "Updating...",
    "form.cleared": "Form cleared",
    "form.reset": "Form reset",
    "message.roomAdded": "Room added successfully",
    "message.roomUpdated": "Room updated successfully",
    "message.roomDeleted": "Room deleted successfully",
    "message.categoryCreated": "Category created successfully",
    "message.categoryUpdated": "Category updated successfully",
    "message.categoryDeleted": "Category deleted successfully",
    "message.error.roomAdd": "Failed to add room",
    "message.error.roomUpdate": "Failed to update room",
    "message.error.unexpected": "An unexpected error occurred",
    "dialog.addRoom.title": "Add New Room",
    "dialog.addRoom.description": "Create a new room listing.",
    "dialog.editRoom.title": "Edit Room",
    "dialog.editRoom.description": "Edit details for room",
    "dialog.categories.title": "Manage Room Categories",
    "dialog.categories.description": "Add, edit, or delete room categories.",
    "category.name": "Category Name",
    "category.name.required": "Category name is required",
    "category.name.placeholder": "Enter category name",
    "category.add": "Add Category",
    "category.edit": "Edit Category",
    "category.delete": "Delete Category",
    "category.view": "View Category",
    "category.select": "Select a category",
    "category.custom": "Custom Category",
    "category.noCategories": "No categories available",
    "category.noResults": "No categories found matching",
    "category.existing": "Existing Categories",
    "category.deleteConfirm": "Are you sure you want to delete this category? This action cannot be undone.",
    "category.rooms": "rooms",
    "time.created": "Created",
    "action.confirm": "Confirm",
    "action.cancel": "Cancel",
    "action.save": "Save",
    "action.edit": "Edit",
    "action.delete": "Delete",
    "action.add": "Add",
    "action.view": "View",
    "action.back": "Back",
    "action.next": "Next",
    "action.previous": "Previous",
    "action.search": "Search",
    "action.clear": "Clear",
    "action.close": "Close",
    "action.open": "Open",
    "action.submit": "Submit",
    "action.reset": "Reset",
    "action.create": "Create",
    "action.update": "Update",
    "action.details": "Details",
    "action.actions": "Actions",
    "action.noData": "No data available",
    "action.saving": "Saving...",
    "table.showing": "Showing",
    "table.of": "of",
    "table.page": "Page",
    "roomTable.searchPlaceholder": "Search rooms by number, category, or description...",
    "roomTable.table": "Table",
    "roomTable.grid": "Grid",
    "roomTable.rows": "Rows",
    "roomTable.sort": "Sort",
    "roomTable.resultsFound": "room(s) found",
    "roomTable.noRoomsFound": "No rooms found.",
    "roomTable.noRoomsMatching": "No rooms found matching",
    "roomTable.image": "Image",
    "roomTable.room": "Room",
    "roomTable.category": "Category",
    "roomTable.price": "Price",
    "roomTable.description": "Description",
    "roomTable.actions": "Actions",
    "roomTable.sortOptions.roomNumberAsc": "Room Number (A-Z)",
    "roomTable.sortOptions.roomNumberDesc": "Room Number (Z-A)",
    "roomTable.sortOptions.categoryAsc": "Category (A-Z)",
    "roomTable.sortOptions.categoryDesc": "Category (Z-A)",
    "roomTable.sortOptions.priceLowHigh": "Price (Low to High)",
    "roomTable.sortOptions.priceHighLow": "Price (High to Low)",
    "roomTable.sortOptions.newestFirst": "Newest First",
    "roomTable.sortOptions.oldestFirst": "Oldest First",
    "roomTable.showing": "Showing",
    "roomTable.of": "of",
    "roomTable.rooms": "rooms",
    "roomTable.page": "Page",
    "roomTable.previous": "Previous",
    "roomTable.next": "Next",
    "roomTable.viewDetails": "View Details",
    "roomTable.edit": "Edit",
    "roomTable.viewImages": "View Images",
    "roomTable.delete": "Delete",
    "roomTable.openMenu": "Open menu",
    "roomTable.roomDetails": "Room Details",
    "roomTable.roomDetailsDescription": "Detailed information about the room.",
    "roomTable.roomNumber": "Room Number",
    "roomTable.createdAt": "Created",
    "roomTable.confirmDeletion": "Confirm Deletion",
    "roomTable.deleteConfirmMessage": "Are you sure you want to delete this room? This action cannot be undone.",
    "roomTable.cancel": "Cancel",
    "roomTable.deleting": "Deleting...",
    "roomTable.unknownCategory": "Unknown Category",
  },
  es: {
    loading: "Cargando...",
    error: "Error",
    success: "Éxito",
    confirm: "Confirmar",
    cancel: "Cancelar",
    save: "Guardar",
    edit: "Editar",
    delete: "Eliminar",
    add: "Agregar",
    view: "Ver",
    back: "Atrás",
    next: "Siguiente",
    previous: "Anterior",
    search: "Buscar",
    clear: "Limpiar",
    close: "Cerrar",
    open: "Abrir",
    submit: "Enviar",
    reset: "Restablecer",
    create: "Crear",
    update: "Actualizar",
    details: "Detalles",
    actions: "Acciones",
    noData: "No hay datos disponibles",
    pageNotFound: "Página no encontrada",
    unauthorized: "No autorizado",
    forbidden: "Prohibido",
    internalServerError: "Error interno del servidor",
    badRequest: "Solicitud incorrecta",
    notFound: "No encontrado",
    ok: "OK",
    yes: "Sí",
    no: "No",
    today: "Hoy",
    yesterday: "Ayer",
    tomorrow: "Mañana",
    now: "Ahora",
    "settings.title": "Configuración",
    "settings.currency": "Moneda",
    "settings.language": "Idioma",
    "settings.policy": "Política",
    "settings.currency.description": "Elige tu moneda preferida.",
    "settings.language.description": "Selecciona tu idioma preferido.",
    "language.current": "Actual",
    "language.select": "Seleccionar",
    "language.search": "Buscar",
    "language.save": "Guardar",
    "language.changed": "Idioma cambiado a",
    "language.preview": "Vista previa",
    "language.region": "Región",
    "language.direction": "Dirección",
    "language.font": "Fuente",
    "rooms.add": "Agregar Habitación",
    "rooms.edit": "Editar Habitación",
    "rooms.delete": "Eliminar Habitación",
    "rooms.title": "Habitación",
    "form.roomNumber": "Número de Habitación",
    "form.roomNumber.required": "El número de habitación es obligatorio",
    "form.roomNumber.placeholder": "Ingresa el número de habitación",
    "form.category": "Categoría",
    "form.category.required": "La categoría es obligatoria",
    "form.category.placeholder": "Selecciona una categoría",
    "form.price.baseNight": "Precio Base por Noche",
    "form.price.perHour": "Precio por Hora",
    "form.price.base": "Precio Base",
    "form.price.required": "El precio es obligatorio",
    "form.price.invalid": "Por favor, ingresa un precio válido",
    "form.description": "Descripción",
    "form.description.placeholder": "Ingresa la descripción de la habitación",
    "form.images": "Imágenes de la Habitación",
    "form.images.remove": "Eliminar imagen",
    "form.policy.details": "Detalles de la Política",
    "form.policy.night": "Duración de la Noche",
    "form.policy.checkin": "Hora de Check-in",
    "form.policy.checkout": "Hora de Check-out",
    "form.policy.lateCheckout": "Tarifas de Check-out Tardío",
    "form.policy.earlyCheckin": "Tarifas de Check-in Temprano",
    "form.policy.configured": "configurado",
    "form.policy.baseHours": "Horas Base",
    "form.policy.hours": "horas",
    "form.policy.overtime": "Tarifas de Tiempo Extra",
    "form.policy.earlyCheckoutFee": "Tarifa de Check-out Temprano",
    "form.policy.mixed": "Política Mixta",
    "form.policy.defaultMode": "Modo de Reserva Predeterminado",
    "form.policy.nightly": "Por Noche",
    "form.policy.flexible": "Flexible",
    "form.preview": "Vista Previa",
    "form.clearForm": "Limpiar Formulario",
    "form.resetForm": "Restablecer Formulario",
    "form.adding": "Agregando...",
    "form.updating": "Actualizando...",
    "form.cleared": "Formulario limpiado",
    "form.reset": "Formulario restablecido",
    "message.roomAdded": "Habitación agregada exitosamente",
    "message.roomUpdated": "Habitación actualizada exitosamente",
    "message.roomDeleted": "Habitación eliminada exitosamente",
    "message.categoryCreated": "Categoría creada exitosamente",
    "message.categoryUpdated": "Categoría actualizada exitosamente",
    "message.categoryDeleted": "Categoría eliminada exitosamente",
    "message.error.roomAdd": "Error al agregar habitación",
    "message.error.roomUpdate": "Error al actualizar habitación",
    "message.error.unexpected": "Ocurrió un error inesperado",
    "dialog.addRoom.title": "Agregar Nueva Habitación",
    "dialog.addRoom.description": "Crea una nueva lista de habitaciones.",
    "dialog.editRoom.title": "Editar Habitación",
    "dialog.editRoom.description": "Editar detalles de la habitación",
    "dialog.categories.title": "Administrar Categorías de Habitación",
    "dialog.categories.description": "Agregar, editar o eliminar categorías de habitación.",
    "category.name": "Nombre de la Categoría",
    "category.name.required": "El nombre de la categoría es obligatorio",
    "category.name.placeholder": "Ingresa el nombre de la categoría",
    "category.add": "Agregar Categoría",
    "category.edit": "Editar Categoría",
    "category.delete": "Eliminar Categoría",
    "category.view": "Ver Categoría",
    "category.select": "Selecciona una categoría",
    "category.custom": "Categoría Personalizada",
    "category.noCategories": "No hay categorías disponibles",
    "category.noResults": "No se encontraron categorías que coincidan con",
    "category.existing": "Categorías Existentes",
    "category.deleteConfirm": "¿Estás seguro de que quieres eliminar esta categoría? Esta acción no se puede deshacer.",
    "category.rooms": "habitaciones",
    "time.created": "Creado",
    "action.confirm": "Confirmar",
    "action.cancel": "Cancelar",
    "action.save": "Guardar",
    "action.edit": "Editar",
    "action.delete": "Eliminar",
    "action.add": "Agregar",
    "action.view": "Ver",
    "action.back": "Atrás",
    "action.next": "Siguiente",
    "action.previous": "Anterior",
    "action.search": "Buscar",
    "action.clear": "Limpiar",
    "action.close": "Cerrar",
    "action.open": "Abrir",
    "action.submit": "Enviar",
    "action.reset": "Restablecer",
    "action.create": "Crear",
    "action.update": "Actualizar",
    "action.details": "Detalles",
    "action.actions": "Acciones",
    "action.noData": "No hay datos disponibles",
    "action.saving": "Guardando...",
    "table.showing": "Mostrando",
    "table.of": "de",
    "table.page": "Página",
    "roomTable.searchPlaceholder": "Buscar habitaciones por número, categoría o descripción...",
    "roomTable.table": "Tabla",
    "roomTable.grid": "Cuadrícula",
    "roomTable.rows": "Filas",
    "roomTable.sort": "Ordenar",
    "roomTable.resultsFound": "habitacion(es) encontrada(s)",
    "roomTable.noRoomsFound": "No se encontraron habitaciones.",
    "roomTable.noRoomsMatching": "No se encontraron habitaciones que coincidan con",
    "roomTable.image": "Imagen",
    "roomTable.room": "Habitación",
    "roomTable.category": "Categoría",
    "roomTable.price": "Precio",
    "roomTable.description": "Descripción",
    "roomTable.actions": "Acciones",
    "roomTable.sortOptions.roomNumberAsc": "Número de habitación (A-Z)",
    "roomTable.sortOptions.roomNumberDesc": "Número de habitación (Z-A)",
    "roomTable.sortOptions.categoryAsc": "Categoría (A-Z)",
    "roomTable.sortOptions.categoryDesc": "Categoría (Z-A)",
    "roomTable.sortOptions.priceLowHigh": "Precio (Bajo a Alto)",
    "roomTable.sortOptions.priceHighLow": "Precio (Alto a Bajo)",
    "roomTable.sortOptions.newestFirst": "Más nuevo primero",
    "roomTable.sortOptions.oldestFirst": "Más antiguo primero",
    "roomTable.showing": "Mostrando",
    "roomTable.of": "de",
    "roomTable.rooms": "habitaciones",
    "roomTable.page": "Página",
    "roomTable.previous": "Anterior",
    "roomTable.next": "Siguiente",
    "roomTable.viewDetails": "Ver detalles",
    "roomTable.edit": "Editar",
    "roomTable.viewImages": "Ver imágenes",
    "roomTable.delete": "Eliminar",
    "roomTable.openMenu": "Abrir menú",
    "roomTable.roomDetails": "Detalles de la habitación",
    "roomTable.roomDetailsDescription": "Información detallada sobre la habitación.",
    "roomTable.roomNumber": "Número de habitación",
    "roomTable.createdAt": "Creado",
    "roomTable.confirmDeletion": "Confirmar eliminación",
    "roomTable.deleteConfirmMessage":
      "¿Está seguro de que desea eliminar esta habitación? Esta acción no se puede deshacer.",
    "roomTable.cancel": "Cancelar",
    "roomTable.deleting": "Eliminando...",
    "roomTable.unknownCategory": "Categoría desconocida",
  },
  fr: {
    loading: "Chargement...",
    error: "Erreur",
    success: "Succès",
    confirm: "Confirmer",
    cancel: "Annuler",
    save: "Enregistrer",
    edit: "Modifier",
    delete: "Supprimer",
    add: "Ajouter",
    view: "Voir",
    back: "Retour",
    next: "Suivant",
    previous: "Précédent",
    search: "Rechercher",
    clear: "Effacer",
    close: "Fermer",
    open: "Ouvrir",
    submit: "Soumettre",
    reset: "Réinitialiser",
    create: "Créer",
    update: "Mettre à jour",
    details: "Détails",
    actions: "Actions",
    noData: "Aucune donnée disponible",
    pageNotFound: "Page non trouvée",
    unauthorized: "Non autorisé",
    forbidden: "Interdit",
    internalServerError: "Erreur interne du serveur",
    badRequest: "Mauvaise requête",
    notFound: "Non trouvé",
    ok: "OK",
    yes: "Oui",
    no: "Non",
    today: "Aujourd'hui",
    yesterday: "Hier",
    tomorrow: "Demain",
    now: "Maintenant",
    "settings.title": "Paramètres",
    "settings.currency": "Devise",
    "settings.language": "Langue",
    "settings.policy": "Politique",
    "settings.currency.description": "Choisissez votre devise préférée.",
    "settings.language.description": "Sélectionnez votre langue préférée.",
    "language.current": "Actuelle",
    "language.select": "Sélectionner",
    "language.search": "Rechercher",
    "language.save": "Enregistrer",
    "language.changed": "Langue changée en",
    "language.preview": "Aperçu",
    "language.region": "Région",
    "language.direction": "Direction",
    "language.font": "Police",
    "rooms.add": "Ajouter une Chambre",
    "rooms.edit": "Modifier la Chambre",
    "rooms.delete": "Supprimer la Chambre",
    "rooms.title": "Chambre",
    "form.roomNumber": "Numéro de Chambre",
    "form.roomNumber.required": "Le numéro de chambre est obligatoire",
    "form.roomNumber.placeholder": "Entrez le numéro de chambre",
    "form.category": "Catégorie",
    "form.category.required": "La catégorie est obligatoire",
    "form.category.placeholder": "Sélectionnez une catégorie",
    "form.price.baseNight": "Prix de Base par Nuit",
    "form.price.perHour": "Prix par Heure",
    "form.price.base": "Prix de Base",
    "form.price.required": "Le prix est obligatoire",
    "form.price.invalid": "Veuillez entrer un prix valide",
    "form.description": "Description",
    "form.description.placeholder": "Entrez la description de la chambre",
    "form.images": "Images de la Chambre",
    "form.images.remove": "Supprimer l'image",
    "form.policy.details": "Détails de la Politique",
    "form.policy.night": "Durée de la Nuit",
    "form.policy.checkin": "Heure d'Arrivée",
    "form.policy.checkout": "Heure de Départ",
    "form.policy.lateCheckout": "Frais de Départ Tardif",
    "form.policy.earlyCheckin": "Frais d'Arrivée Anticipée",
    "form.policy.configured": "configuré",
    "form.policy.baseHours": "Heures de Base",
    "form.policy.hours": "heures",
    "form.policy.overtime": "Frais de Temps Supplémentaire",
    "form.policy.earlyCheckoutFee": "Frais de Départ Anticipé",
    "form.policy.mixed": "Politique Mixte",
    "form.policy.defaultMode": "Mode de Réservation par Défaut",
    "form.policy.nightly": "Par Nuit",
    "form.policy.flexible": "Flexible",
    "form.preview": "Aperçu",
    "form.clearForm": "Effacer le Formulaire",
    "form.resetForm": "Réinitialiser le Formulaire",
    "form.adding": "Ajout...",
    "form.updating": "Mise à jour...",
    "form.cleared": "Formulaire effacé",
    "form.reset": "Formulaire réinitialisé",
    "message.roomAdded": "Chambre ajoutée avec succès",
    "message.roomUpdated": "Chambre mise à jour avec succès",
    "message.roomDeleted": "Chambre supprimée avec succès",
    "message.categoryCreated": "Catégorie créée avec succès",
    "message.categoryUpdated": "Catégorie mise à jour avec succès",
    "message.categoryDeleted": "Catégorie supprimée avec succès",
    "message.error.roomAdd": "Échec de l'ajout de la chambre",
    "message.error.roomUpdate": "Échec de la mise à jour de la chambre",
    "message.error.unexpected": "Une erreur inattendue s'est produite",
    "dialog.addRoom.title": "Ajouter une Nouvelle Chambre",
    "dialog.addRoom.description": "Créer une nouvelle liste de chambres.",
    "dialog.editRoom.title": "Modifier la Chambre",
    "dialog.editRoom.description": "Modifier les détails de la chambre",
    "dialog.categories.title": "Gérer les Catégories de Chambres",
    "dialog.categories.description": "Ajouter, modifier ou supprimer des catégories de chambres.",
    "category.name": "Nom de la Catégorie",
    "category.name.required": "Le nom de la catégorie est obligatoire",
    "category.name.placeholder": "Entrez le nom de la catégorie",
    "category.add": "Ajouter une Catégorie",
    "category.edit": "Modifier la Catégorie",
    "category.delete": "Supprimer la Catégorie",
    "category.view": "Voir la Catégorie",
    "category.select": "Sélectionnez une catégorie",
    "category.custom": "Catégorie Personnalisée",
    "category.noCategories": "Aucune catégorie disponible",
    "category.noResults": "Aucune catégorie trouvée correspondant à",
    "category.existing": "Catégories Existantes",
    "category.deleteConfirm": "Êtes-vous sûr de vouloir supprimer cette catégorie ? Cette action est irréversible.",
    "category.rooms": "chambres",
    "time.created": "Créé",
    "action.confirm": "Confirmer",
    "action.cancel": "Annuler",
    "action.save": "Enregistrer",
    "action.edit": "Modifier",
    "action.delete": "Supprimer",
    "action.add": "Ajouter",
    "action.view": "Voir",
    "action.back": "Retour",
    "action.next": "Suivant",
    "action.previous": "Précédent",
    "action.search": "Rechercher",
    "action.clear": "Effacer",
    "action.close": "Fermer",
    "action.open": "Ouvrir",
    "action.submit": "Soumettre",
    "action.reset": "Réinitialiser",
    "action.create": "Créer",
    "action.update": "Mettre à jour",
    "action.details": "Détails",
    "action.actions": "Actions",
    "action.noData": "Aucune donnée disponible",
    "action.saving": "Enregistrement...",
    "table.showing": "Montrant",
    "table.of": "de",
    "table.page": "Page",
    "roomTable.searchPlaceholder": "Rechercher des chambres par numéro, catégorie ou description...",
    "roomTable.table": "Table",
    "roomTable.grid": "Grille",
    "roomTable.rows": "Rangées",
    "roomTable.sort": "Trier",
    "roomTable.resultsFound": "chambre(s) trouvée(s)",
    "roomTable.noRoomsFound": "Aucune chambre trouvée.",
    "roomTable.noRoomsMatching": "Aucune chambre trouvée correspondant à",
    "roomTable.image": "Image",
    "roomTable.room": "Chambre",
    "roomTable.category": "Catégorie",
    "roomTable.price": "Prix",
    "roomTable.description": "Description",
    "roomTable.actions": "Actions",
    "roomTable.sortOptions.roomNumberAsc": "Numéro de chambre (A-Z)",
    "roomTable.sortOptions.roomNumberDesc": "Numéro de chambre (Z-A)",
    "roomTable.sortOptions.categoryAsc": "Catégorie (A-Z)",
    "roomTable.sortOptions.categoryDesc": "Catégorie (Z-A)",
    "roomTable.sortOptions.priceLowHigh": "Prix (Bas à Haut)",
    "roomTable.sortOptions.priceHighLow": "Prix (Haut à Bas)",
    "roomTable.sortOptions.newestFirst": "Le plus récent d'abord",
    "roomTable.sortOptions.oldestFirst": "Le plus ancien d'abord",
    "roomTable.showing": "Montrant",
    "roomTable.of": "de",
    "roomTable.rooms": "chambres",
    "roomTable.page": "Page",
    "roomTable.previous": "Précédent",
    "roomTable.next": "Suivant",
    "roomTable.viewDetails": "Voir les détails",
    "roomTable.edit": "Modifier",
    "roomTable.viewImages": "Voir les images",
    "roomTable.delete": "Supprimer",
    "roomTable.openMenu": "Ouvrir le menu",
    "roomTable.roomDetails": "Détails de la chambre",
    "roomTable.roomDetailsDescription": "Informations détaillées sur la chambre.",
    "roomTable.roomNumber": "Numéro de chambre",
    "roomTable.createdAt": "Créé",
    "roomTable.confirmDeletion": "Confirmer la suppression",
    "roomTable.deleteConfirmMessage":
      "Êtes-vous sûr de vouloir supprimer cette chambre ? Cette action est irréversible.",
    "roomTable.cancel": "Annuler",
    "roomTable.deleting": "Suppression...",
    "roomTable.unknownCategory": "Catégorie inconnue",
  },
  de: {
    loading: "Wird geladen...",
  error: "Fehler",
  success: "Erfolg",
  confirm: "Bestätigen",
  cancel: "Abbrechen",
  save: "Speichern",
  edit: "Bearbeiten",
  delete: "Löschen",
  add: "Hinzufügen",
  view: "Anzeigen",
  back: "Zurück",
  next: "Weiter",
  previous: "Vorherige",
  search: "Suchen",
  clear: "Löschen",
  close: "Schließen",
  open: "Öffnen",
  submit: "Absenden",
  reset: "Zurücksetzen",
  create: "Erstellen",
  update: "Aktualisieren",
  details: "Details",
  actions: "Aktionen",
  noData: "Keine Daten verfügbar",
  pageNotFound: "Seite nicht gefunden",
  unauthorized: "Nicht autorisiert",
  forbidden: "Verboten",
  internalServerError: "Interner Serverfehler",
  badRequest: "Fehlerhafte Anfrage",
  notFound: "Nicht gefunden",
  ok: "OK",
  yes: "Ja",
  no: "Nein",
  today: "Heute",
  yesterday: "Gestern",
  tomorrow: "Morgen",
  now: "Jetzt",
  "settings.title": "Einstellungen",
  "settings.currency": "Währung",
  "settings.language": "Sprache",
  "settings.policy": "Richtlinie",
  "settings.currency.description": "Wählen Sie Ihre bevorzugte Währung.",
  "settings.language.description": "Wählen Sie Ihre bevorzugte Sprache.",
  "language.current": "Aktuell",
  "language.select": "Auswählen",
  "language.search": "Suchen",
  "language.save": "Speichern",
  "language.changed": "Sprache geändert zu",
  "language.preview": "Vorschau",
  "language.region": "Region",
  "language.direction": "Richtung",
  "language.font": "Schriftart",
  "rooms.add": "Zimmer hinzufügen",
  "rooms.edit": "Zimmer bearbeiten",
  "rooms.delete": "Zimmer löschen",
  "rooms.title": "Zimmer",
  "form.roomNumber": "Zimmernummer",
  "form.roomNumber.required": "Zimmernummer ist erforderlich",
  "form.roomNumber.placeholder": "Zimmernummer eingeben",
  "form.category": "Kategorie",
  "form.category.required": "Kategorie ist erforderlich",
  "form.category.placeholder": "Kategorie auswählen",
  "form.price.baseNight": "Basispreis pro Nacht",
  "form.price.perHour": "Preis pro Stunde",
  "form.price.base": "Basispreis",
  "form.price.required": "Preis ist erforderlich",
  "form.price.invalid": "Bitte geben Sie einen gültigen Preis ein",
  "form.description": "Beschreibung",
  "form.description.placeholder": "Zimmerbeschreibung eingeben",
  "form.images": "Zimmerbilder",
  "form.images.remove": "Bild entfernen",
  "form.policy.details": "Richtlinien-Details",
  "form.policy.night": "Nachtdauer",
  "form.policy.checkin": "Check-in-Zeit",
  "form.policy.checkout": "Check-out-Zeit",
  "form.policy.lateCheckout": "Späte Check-out-Gebühren",
  "form.policy.earlyCheckin": "Frühe Check-in-Gebühren",
  "form.policy.configured": "Konfiguriert",
  "form.policy.baseHours": "Basisstunden",
  "form.policy.hours": "Stunden",
  "form.policy.overtime": "Überstunden-Gebühren",
  "form.policy.earlyCheckoutFee": "Frühe Check-out-Gebühr",
  "form.policy.mixed": "Gemischte Richtlinie",
  "form.policy.defaultMode": "Standardbuchungsmodus",
  "form.policy.nightly": "Nächtlich",
  "form.policy.flexible": "Flexibel",
  "form.preview": "Vorschau",
  "form.clearForm": "Formular löschen",
  "form.resetForm": "Formular zurücksetzen",
  "form.adding": "Hinzufügen...",
  "form.updating": "Aktualisieren...",
  "form.cleared": "Formular gelöscht",
  "form.reset": "Formular zurückgesetzt",
  "message.roomAdded": "Zimmer erfolgreich hinzugefügt",
  "message.roomUpdated": "Zimmer erfolgreich aktualisiert",
  "message.roomDeleted": "Zimmer erfolgreich gelöscht",
  "message.categoryCreated": "Kategorie erfolgreich erstellt",
  "message.categoryUpdated": "Kategorie erfolgreich aktualisiert",
  "message.categoryDeleted": "Kategorie erfolgreich gelöscht",
  "message.error.roomAdd": "Fehler beim Hinzufügen des Zimmers",
  "message.error.roomUpdate": "Fehler beim Aktualisieren des Zimmers",
  "message.error.unexpected": "Ein unerwarteter Fehler ist aufgetreten",
  "dialog.addRoom.title": "Neues Zimmer hinzufügen",
  "dialog.addRoom.description": "Erstellen Sie ein neues Zimmer.",
  "dialog.editRoom.title": "Zimmer bearbeiten",
  "dialog.editRoom.description": "Bearbeiten Sie die Details des Zimmers.",
  "dialog.categories.title": "Kategorien verwalten",
  "dialog.categories.description": "Hinzufügen, Bearbeiten oder Löschen von Kategorien.",
  "category.name": "Kategoriename",
  "category.name.required": "Kategoriename ist erforderlich",
  "category.name.placeholder": "Kategoriename eingeben",
  "category.add": "Kategorie hinzufügen",
  "category.edit": "Kategorie bearbeiten",
  "category.delete": "Kategorie löschen",
  "category.view": "Kategorie anzeigen",
  "category.select": "Kategorie auswählen",
  "category.custom": "Benutzerdefinierte Kategorie",
  "category.noCategories": "Keine Kategorien verfügbar",
  "category.noResults": "Keine Kategorien gefunden",
  "category.existing": "Vorhandene Kategorien",
  "category.deleteConfirm": "Sind Sie sicher, dass Sie diese Kategorie löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.",
  "category.rooms": "Zimmer",
  "time.created": "Erstellt",
  "action.confirm": "Bestätigen",
  "action.cancel": "Abbrechen",
  "action.save": "Speichern",
  "action.edit": "Bearbeiten",
  "action.delete": "Löschen",
  "action.add": "Hinzufügen",
  "action.view": "Anzeigen",
  "action.back": "Zurück",
  "action.next": "Weiter",
  "action.previous": "Vorherige",
  "action.search": "Suchen",
  "action.clear": "Löschen",
  "action.close": "Schließen",
  "action.open": "Öffnen",
  "action.submit": "Absenden",
  "action.reset": "Zurücksetzen",
  "action.create": "Erstellen",
  "action.update": "Aktualisieren",
  "action.details": "Details",
  "action.actions": "Aktionen",
  "action.noData": "Keine Daten verfügbar",
  "action.saving": "Speichern...",
  "table.showing": "Zeige",
  "table.of": "von",
  "table.page": "Seite",
  "roomTable.searchPlaceholder": "Zimmer nach Nummer, Kategorie oder Beschreibung suchen...",
  "roomTable.table": "Tabelle",
  "roomTable.grid": "Raster",
  "roomTable.rows": "Zeilen",
  "roomTable.sort": "Sortieren",
  "roomTable.resultsFound": "Zimmer gefunden",
  "roomTable.noRoomsFound": "Keine Zimmer gefunden.",
  "roomTable.noRoomsMatching": "Keine Zimmer gefunden, die übereinstimmen",
  "roomTable.image": "Bild",
  "roomTable.room": "Zimmer",
  "roomTable.category": "Kategorie",
  "roomTable.price": "Preis",
  "roomTable.description": "Beschreibung",
  "roomTable.actions": "Aktionen",
  "roomTable.sortOptions.roomNumberAsc": "Zimmernummer (A-Z)",
  "roomTable.sortOptions.roomNumberDesc": "Zimmernummer (Z-A)",
  "roomTable.sortOptions.categoryAsc": "Kategorie (A-Z)",
  "roomTable.sortOptions.categoryDesc": "Kategorie (Z-A)",
  "roomTable.sortOptions.priceLowHigh": "Preis (Niedrig bis Hoch)",
  "roomTable.sortOptions.priceHighLow": "Preis (Hoch bis Niedrig)",
  "roomTable.sortOptions.newestFirst": "Neueste zuerst",
  "roomTable.sortOptions.oldestFirst": "Älteste zuerst",
  "roomTable.showing": "Zeige",
  "roomTable.of": "von",
  "roomTable.rooms": "Zimmer",
  "roomTable.page": "Seite",
  "roomTable.previous": "Vorherige",
  "roomTable.next": "Weiter",
  "roomTable.viewDetails": "Details anzeigen",
  "roomTable.edit": "Bearbeiten",
  "roomTable.viewImages": "Bilder anzeigen",
  "roomTable.delete": "Löschen",
  "roomTable.openMenu": "Menü öffnen",
  "roomTable.roomDetails": "Zimmerdetails",
  "roomTable.roomDetailsDescription": "Detaillierte Informationen über das Zimmer.",
  "roomTable.roomNumber": "Zimmernummer",
  "roomTable.createdAt": "Erstellt am",
  "roomTable.confirmDeletion": "Löschung bestätigen",
  "roomTable.deleteConfirmMessage": "Sind Sie sicher, dass Sie dieses Zimmer löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.",
  "roomTable.cancel": "Abbrechen",
  "roomTable.deleting": "Löschen...",
  "roomTable.unknownCategory": "Unbekannte Kategorie",

  },
  it: {
    loading: "Caricamento...",
  error: "Errore",
  success: "Successo",
  confirm: "Conferma",
  cancel: "Annulla",
  save: "Salva",
  edit: "Modifica",
  delete: "Elimina",
  add: "Aggiungi",
  view: "Visualizza",
  back: "Indietro",
  next: "Avanti",
  previous: "Precedente",
  search: "Cerca",
  clear: "Pulisci",
  close: "Chiudi",
  open: "Apri",
  submit: "Invia",
  reset: "Reimposta",
  create: "Crea",
  update: "Aggiorna",
  details: "Dettagli",
  actions: "Azioni",
  noData: "Nessun dato disponibile",
  pageNotFound: "Pagina non trovata",
  unauthorized: "Non autorizzato",
  forbidden: "Vietato",
  internalServerError: "Errore interno del server",
  badRequest: "Richiesta non valida",
  notFound: "Non trovato",
  ok: "OK",
  yes: "Sì",
  no: "No",
  today: "Oggi",
  yesterday: "Ieri",
  tomorrow: "Domani",
  now: "Adesso",
  "settings.title": "Impostazioni",
  "settings.currency": "Valuta",
  "settings.language": "Lingua",
  "settings.policy": "Politica",
  "settings.currency.description": "Scegli la tua valuta preferita.",
  "settings.language.description": "Seleziona la tua lingua preferita.",
  "language.current": "Corrente",
  "language.select": "Seleziona",
  "language.search": "Cerca",
  "language.save": "Salva",
  "language.changed": "Lingua modificata in",
  "language.preview": "Anteprima",
  "language.region": "Regione",
  "language.direction": "Direzione",
  "language.font": "Carattere",
  "rooms.add": "Aggiungi stanza",
  "rooms.edit": "Modifica stanza",
  "rooms.delete": "Elimina stanza",
  "rooms.title": "Stanza",
  "form.roomNumber": "Numero di stanza",
  "form.roomNumber.required": "Numero di stanza obbligatorio",
  "form.roomNumber.placeholder": "Inserisci il numero di stanza",
  "form.category": "Categoria",
  "form.category.required": "Categoria obbligatoria",
  "form.category.placeholder": "Seleziona una categoria",
  "form.price.baseNight": "Prezzo base per notte",
  "form.price.perHour": "Prezzo per ora",
  "form.price.base": "Prezzo base",
  "form.price.required": "Prezzo obbligatorio",
  "form.price.invalid": "Per favore inserisci un prezzo valido",
  "form.description": "Descrizione",
  "form.description.placeholder": "Inserisci la descrizione della stanza",
  "form.images": "Immagini della stanza",
  "form.images.remove": "Rimuovi immagine",
  "form.policy.details": "Dettagli della politica",
  "form.policy.night": "Durata della notte",
  "form.policy.checkin": "Orario di check-in",
  "form.policy.checkout": "Orario di check-out",
  "form.policy.lateCheckout": "Tasse per check-out ritardato",
  "form.policy.earlyCheckin": "Tasse per check-in anticipato",
  "form.policy.configured": "Configurato",
  "form.policy.baseHours": "Ore base",
  "form.policy.hours": "ore",
  "form.policy.overtime": "Tasse per straordinario",
  "form.policy.earlyCheckoutFee": "Tassa per check-out anticipato",
  "form.policy.mixed": "Politica mista",
  "form.policy.defaultMode": "Modalità di prenotazione predefinita",
  "form.policy.nightly": "Notturno",
  "form.policy.flexible": "Flessibile",
  "form.preview": "Anteprima",
  "form.clearForm": "Pulisci il modulo",
  "form.resetForm": "Reimposta il modulo",
  "form.adding": "Aggiunta...",
  "form.updating": "Aggiornamento...",
  "form.cleared": "Modulo pulito",
  "form.reset": "Modulo reimpostato",
  "message.roomAdded": "Stanza aggiunta con successo",
  "message.roomUpdated": "Stanza aggiornata con successo",
  "message.roomDeleted": "Stanza eliminata con successo",
  "message.categoryCreated": "Categoria creata con successo",
  "message.categoryUpdated": "Categoria aggiornata con successo",
  "message.categoryDeleted": "Categoria eliminata con successo",
  "message.error.roomAdd": "Errore durante l'aggiunta della stanza",
  "message.error.roomUpdate": "Errore durante l'aggiornamento della stanza",
  "message.error.unexpected": "Si è verificato un errore imprevisto",
  "dialog.addRoom.title": "Aggiungi nuova stanza",
  "dialog.addRoom.description": "Crea una nuova stanza.",
  "dialog.editRoom.title": "Modifica stanza",
  "dialog.editRoom.description": "Modifica i dettagli della stanza.",
  "dialog.categories.title": "Gestisci categorie",
  "dialog.categories.description": "Aggiungi, modifica o elimina categorie.",
  "category.name": "Nome della categoria",
  "category.name.required": "Nome della categoria obbligatorio",
  "category.name.placeholder": "Inserisci il nome della categoria",
  "category.add": "Aggiungi categoria",
  "category.edit": "Modifica categoria",
  "category.delete": "Elimina categoria",
  "category.view": "Visualizza categoria",
  "category.select": "Seleziona una categoria",
  "category.custom": "Categoria personalizzata",
  "category.noCategories": "Nessuna categoria disponibile",
  "category.noResults": "Nessuna categoria trovata",
  "category.existing": "Categorie esistenti",
  "category.deleteConfirm": "Sei sicuro di voler eliminare questa categoria? Questa azione non può essere annullata.",
  "category.rooms": "stanze",
  "time.created": "Creato",
  "action.confirm": "Conferma",
  "action.cancel": "Annulla",
  "action.save": "Salva",
  "action.edit": "Modifica",
  "action.delete": "Elimina",
  "action.add": "Aggiungi",
  "action.view": "Visualizza",
  "action.back": "Indietro",
  "action.next": "Avanti",
  "action.previous": "Precedente",
  "action.search": "Cerca",
  "action.clear": "Pulisci",
  "action.close": "Chiudi",
  "action.open": "Apri",
  "action.submit": "Invia",
  "action.reset": "Reimposta",
  "action.create": "Crea",
  "action.update": "Aggiorna",
  "action.details": "Dettagli",
  "action.actions": "Azioni",
  "action.noData": "Nessun dato disponibile",
  "action.saving": "Salvataggio...",
  "table.showing": "Visualizzazione",
  "table.of": "di",
  "table.page": "Pagina",
  "roomTable.searchPlaceholder": "Cerca stanze per numero, categoria o descrizione...",
  "roomTable.table": "Tabella",
  "roomTable.grid": "Griglia",
  "roomTable.rows": "Righe",
  "roomTable.sort": "Ordina",
  "roomTable.resultsFound": "stanze trovate",
  "roomTable.noRoomsFound": "Nessuna stanza trovata.",
  "roomTable.noRoomsMatching": "Nessuna stanza trovata che corrisponda",
  "roomTable.image": "Immagine",
  "roomTable.room": "Stanza",
  "roomTable.category": "Categoria",
  "roomTable.price": "Prezzo",
  "roomTable.description": "Descrizione",
  "roomTable.actions": "Azioni",
  "roomTable.sortOptions.roomNumberAsc": "Numero di stanza (A-Z)",
  "roomTable.sortOptions.roomNumberDesc": "Numero di stanza (Z-A)",
  "roomTable.sortOptions.categoryAsc": "Categoria (A-Z)",
  "roomTable.sortOptions.categoryDesc": "Categoria (Z-A)",
  "roomTable.sortOptions.priceLowHigh": "Prezzo (Basso-Alto)",
  "roomTable.sortOptions.priceHighLow": "Prezzo (Alto-Basso)",
  "roomTable.sortOptions.newestFirst": "Più recenti prima",
  "roomTable.sortOptions.oldestFirst": "Più vecchi prima",
  "roomTable.showing": "Visualizzazione",
  "roomTable.of": "di",
  "roomTable.rooms": "stanze",
  "roomTable.page": "Pagina",
  "roomTable.previous": "Precedente",
  "roomTable.next": "Avanti",
  "roomTable.viewDetails": "Visualizza dettagli",
  "roomTable.edit": "Modifica",
  "roomTable.viewImages": "Visualizza immagini",
  "roomTable.delete": "Elimina",
  "roomTable.openMenu": "Apri menu",
  "roomTable.roomDetails": "Dettagli della stanza",
  "roomTable.roomDetailsDescription": "Informazioni dettagliate sulla stanza.",
  "roomTable.roomNumber": "Numero di stanza",
  "roomTable.createdAt": "Creato il",
  "roomTable.confirmDeletion": "Conferma eliminazione",
  "roomTable.deleteConfirmMessage": "Sei sicuro di voler eliminare questa stanza? Questa azione non può essere annullata.",
  "roomTable.cancel": "Annulla",
  "roomTable.deleting": "Eliminazione...",
  "roomTable.unknownCategory": "Categoria sconosciuta",
  },
  pt: {
    loading: "Carregando...",
  error: "Erro",
  success: "Sucesso",
  confirm: "Confirmar",
  cancel: "Cancelar",
  save: "Salvar",
  edit: "Editar",
  delete: "Excluir",
  add: "Adicionar",
  view: "Visualizar",
  back: "Voltar",
  next: "Próximo",
  previous: "Anterior",
  search: "Pesquisar",
  clear: "Limpar",
  close: "Fechar",
  open: "Abrir",
  submit: "Enviar",
  reset: "Redefinir",
  create: "Criar",
  update: "Atualizar",
  details: "Detalhes",
  actions: "Ações",
  noData: "Nenhum dado disponível",
  pageNotFound: "Página não encontrada",
  unauthorized: "Não autorizado",
  forbidden: "Proibido",
  internalServerError: "Erro interno do servidor",
  badRequest: "Requisição inválida",
  notFound: "Não encontrado",
  ok: "OK",
  yes: "Sim",
  no: "Não",
  today: "Hoje",
  yesterday: "Ontem",
  tomorrow: "Amanhã",
  now: "Agora",
  "settings.title": "Configurações",
  "settings.currency": "Moeda",
  "settings.language": "Idioma",
  "settings.policy": "Política",
  "settings.currency.description": "Escolha sua moeda preferida.",
  "settings.language.description": "Selecione seu idioma preferido.",
  "language.current": "Atual",
  "language.select": "Selecione",
  "language.search": "Pesquisar",
  "language.save": "Salvar",
  "language.changed": "Idioma alterado para",
  "language.preview": "Pré-visualização",
  "language.region": "Região",
  "language.direction": "Direção",
  "language.font": "Fonte",
  "rooms.add": "Adicionar quarto",
  "rooms.edit": "Editar quarto",
  "rooms.delete": "Excluir quarto",
  "rooms.title": "Quarto",
  "form.roomNumber": "Número do quarto",
  "form.roomNumber.required": "Número do quarto é obrigatório",
  "form.roomNumber.placeholder": "Insira o número do quarto",
  "form.category": "Categoria",
  "form.category.required": "Categoria é obrigatória",
  "form.category.placeholder": "Selecione uma categoria",
  "form.price.baseNight": "Preço base por noite",
  "form.price.perHour": "Preço por hora",
  "form.price.base": "Preço base",
  "form.price.required": "Preço é obrigatório",
  "form.price.invalid": "Por favor, insira um preço válido",
  "form.description": "Descrição",
  "form.description.placeholder": "Insira a descrição do quarto",
  "form.images": "Imagens do quarto",
  "form.images.remove": "Remover imagem",
  "form.policy.details": "Detalhes da política",
  "form.policy.night": "Duração da noite",
  "form.policy.checkin": "Horário de check-in",
  "form.policy.checkout": "Horário de check-out",
  "form.policy.lateCheckout": "Taxas de check-out tardio",
  "form.policy.earlyCheckin": "Taxas de check-in antecipado",
  "form.policy.configured": "Configurado",
  "form.policy.baseHours": "Horas base",
  "form.policy.hours": "horas",
  "form.policy.overtime": "Taxas de horas extras",
  "form.policy.earlyCheckoutFee": "Taxa de check-out antecipado",
  "form.policy.mixed": "Política mista",
  "form.policy.defaultMode": "Modo de reserva padrão",
  "form.policy.nightly": "Noturno",
  "form.policy.flexible": "Flexível",
  "form.preview": "Pré-visualização",
  "form.clearForm": "Limpar formulário",
  "form.resetForm": "Redefinir formulário",
  "form.adding": "Adicionando...",
  "form.updating": "Atualizando...",
  "form.cleared": "Formulário limpo",
  "form.reset": "Formulário redefinido",
  "message.roomAdded": "Quarto adicionado com sucesso",
  "message.roomUpdated": "Quarto atualizado com sucesso",
  "message.roomDeleted": "Quarto excluído com sucesso",
  "message.categoryCreated": "Categoria criada com sucesso",
  "message.categoryUpdated": "Categoria atualizada com sucesso",
  "message.categoryDeleted": "Categoria excluída com sucesso",
  "message.error.roomAdd": "Erro ao adicionar quarto",
  "message.error.roomUpdate": "Erro ao atualizar quarto",
  "message.error.unexpected": "Ocorreu um erro inesperado",
  "dialog.addRoom.title": "Adicionar novo quarto",
  "dialog.addRoom.description": "Crie um novo quarto.",
  "dialog.editRoom.title": "Editar quarto",
  "dialog.editRoom.description": "Edite os detalhes do quarto.",
  "dialog.categories.title": "Gerenciar categorias",
  "dialog.categories.description": "Adicionar, editar ou excluir categorias.",
  "category.name": "Nome da categoria",
  "category.name.required": "Nome da categoria é obrigatório",
  "category.name.placeholder": "Insira o nome da categoria",
  "category.add": "Adicionar categoria",
  "category.edit": "Editar categoria",
  "category.delete": "Excluir categoria",
  "category.view": "Visualizar categoria",
  "category.select": "Selecione uma categoria",
  "category.custom": "Categoria personalizada",
  "category.noCategories": "Nenhuma categoria disponível",
  "category.noResults": "Nenhuma categoria encontrada",
  "category.existing": "Categorias existentes",
  "category.deleteConfirm": "Tem certeza de que deseja excluir esta categoria? Esta ação não pode ser desfeita.",
  "category.rooms": "quartos",
  "time.created": "Criado",
  "action.confirm": "Confirmar",
  "action.cancel": "Cancelar",
  "action.save": "Salvar",
  "action.edit": "Editar",
  "action.delete": "Excluir",
  "action.add": "Adicionar",
  "action.view": "Visualizar",
  "action.back": "Voltar",
  "action.next": "Próximo",
  "action.previous": "Anterior",
  "action.search": "Pesquisar",
  "action.clear": "Limpar",
  "action.close": "Fechar",
  "action.open": "Abrir",
  "action.submit": "Enviar",
  "action.reset": "Redefinir",
  "action.create": "Criar",
  "action.update": "Atualizar",
  "action.details": "Detalhes",
  "action.actions": "Ações",
  "action.noData": "Nenhum dado disponível",
  "action.saving": "Salvando...",
  "table.showing": "Mostrando",
  "table.of": "de",
  "table.page": "Página",
  "roomTable.searchPlaceholder": "Pesquisar quartos por número, categoria ou descrição...",
  "roomTable.table": "Tabela",
  "roomTable.grid": "Grade",
  "roomTable.rows": "Linhas",
  "roomTable.sort": "Ordenar",
  "roomTable.resultsFound": "quartos encontrados",
  "roomTable.noRoomsFound": "Nenhum quarto encontrado.",
  "roomTable.noRoomsMatching": "Nenhum quarto encontrado que corresponda",
  "roomTable.image": "Imagem",
  "roomTable.room": "Quarto",
  "roomTable.category": "Categoria",
  "roomTable.price": "Preço",
  "roomTable.description": "Descrição",
  "roomTable.actions": "Ações",
  "roomTable.sortOptions.roomNumberAsc": "Número do quarto (A-Z)",
  "roomTable.sortOptions.roomNumberDesc": "Número do quarto (Z-A)",
  "roomTable.sortOptions.categoryAsc": "Categoria (A-Z)",
  "roomTable.sortOptions.categoryDesc": "Categoria (Z-A)",
  "roomTable.sortOptions.priceLowHigh": "Preço (Baixo-Alto)",
  "roomTable.sortOptions.priceHighLow": "Preço (Alto-Baixo)",
  "roomTable.sortOptions.newestFirst": "Mais recentes primeiro",
  "roomTable.sortOptions.oldestFirst": "Mais antigos primeiro",
  "roomTable.showing": "Mostrando",
  "roomTable.of": "de",
  "roomTable.rooms": "quartos",
  "roomTable.page": "Página",
  "roomTable.previous": "Anterior",
  "roomTable.next": "Próximo",
  "roomTable.viewDetails": "Visualizar detalhes",
  "roomTable.edit": "Editar",
  "roomTable.viewImages": "Visualizar imagens",
  "roomTable.delete": "Excluir",
  "roomTable.openMenu": "Abrir menu",
  "roomTable.roomDetails": "Detalhes do quarto",
  "roomTable.roomDetailsDescription": "Informações detalhadas sobre o quarto.",
  "roomTable.roomNumber": "Número do quarto",
  "roomTable.createdAt": "Criado em",
  "roomTable.confirmDeletion": "Confirmar exclusão",
  "roomTable.deleteConfirmMessage": "Tem certeza de que deseja excluir este quarto? Esta ação não pode ser desfeita.",
  "roomTable.cancel": "Cancelar",
  "roomTable.deleting": "Excluindo...",
  "roomTable.unknownCategory": "Categoria desconhecida",
  },
  ru: {},
  zh: {},
  ja: {},
  ko: {},
  ar: {},
  hi: {},
  nl: {},
}
